[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 300

[Invariant]
runs = 100
depth = 30
fail_on_revert = false

optimizer = true
optimizer_runs = 10000

[fmt]
line_length = 90              
tab_width = 4  
bracket_spacing = true         

multiline_func_header = "attributes_first" 

# 4. Clean-up Logic
sort_imports = true            # Alphabetizes imports automatically
wrap_comments = true           # Wraps long NatSpec to your line_length